"""Add indexes to wishes table

Revision ID: 46bcf48b0e6d
Revises: 
Create Date: 2025-11-21 19:27:45.372679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46bcf48b0e6d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index('idx_user_created', 'wishes', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_user_id', 'wishes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_id', table_name='wishes')
    op.drop_index('idx_user_created', table_name='wishes')
    op.drop_index('idx_users_username', table_name='users')
    # ### end Alembic commands ###
